base/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login/', views.loginPage, name="login"),
    path('registration/', views.registrationPage, name="registration"),

    path('', views.home, name="home"),
    path('detail/<int:id>/', views.detail, name="detail"),
    path('my/', views.my, name="my"),
    path('add/', views.add, name="add"),
    path('edit/<int:id>/', views.edit, name="edit"),
    path('delete/<int:id>/', views.delete, name="delete"),
    # Страница продавца
    path('seller/<int:id>/', views.profileSeller, name='seller'),
    # Ссылка, куда отправляются пост запросы з поиском номера телефона
    path('find_numbers/', views.find_number, name='find_number')
]

simkard/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls.static import static 
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

base/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from phone_field import PhoneField



class PhoneNumber(models.Model):
	operators = [
		(1, 'activ'),
		(2, 'kcell'),
		(3, 'altel'),
		(4, 'tele2'),
		(5, 'beeline'),
		(6, 'izi')
		]
	
	operator = models.PositiveSmallIntegerField(("Оператор"), choices=operators)
	msisdn = PhoneField(blank=True, help_text='Номер телефона', max_length=10)
	price = models.IntegerField('Цена')
	cities = [
		(1, 'Алматы'),
		(2, 'Нур-Султан'),
		(3, 'Шымкент'),
		(4, 'Караганда'),
		(5, 'Павлодар'),
		(6, 'Кызылорда'),
		(7, 'Семей'),
		(8, 'Атырау'),
		(9, 'Актобе'),
		(10, 'Актау'),
		(11, 'Уральск'),
		(12, 'Усть-Каменогорск'),
		(13, 'Кокшетау'),
		(14, 'Петропавловск'),
		(15, 'Талдыкорган'),
		(16, 'Жезказган'),

	]

	is_rent = models.BooleanField(('Аренда'), default=False)

	city = models.PositiveSmallIntegerField(("Город"), choices=cities)
	description = models.CharField('Описание', max_length=200)
	contact_phone = PhoneField(blank=True, help_text='Контактный телефон', max_length=10)
	owner = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='seller', on_delete=models.CASCADE,)
	created = models.DateTimeField(auto_now_add=True)
	active = models.BooleanField(default=False)
	is_top = models.BooleanField(('Топ номер'), default=False)

	def __str__(self):
		return str(self.msisdn)

	class Meta:
		verbose_name = 'Красивый номер'
		verbose_name_plural = 'Красивые номера' 

	@property
	def css_class(self):
		s = self.get_operator_display()
		return "title__text_%s" % s

	@property
	def price_html(self):
		if self.is_rent:
			return "%d тг/меc" % self.price
		return "%d тг" % self.price

	# Получение ссылки на страницу номера
	def get_absolute_url(self):
		return reverse('detail', args=[self.pk])

base/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import *


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class PhoneNumberForm(forms.ModelForm):
    class Meta:
        model = PhoneNumber
        fields = ['operator', 'msisdn', 'city', 'contact_phone', "price", 'is_rent', 'description']

    def __init__(self, *args, **kwargs):
        if "user" in kwargs:
            self.user = kwargs.pop('user')
        super(PhoneNumberForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        m = super(PhoneNumberForm, self).save(commit=False)
        if hasattr(self, "user"):
            m.owner = self.user
        if commit:
            m.save()
        return m

    def clean(self):
        # run the standard clean method first
        cleaned_data = super(PhoneNumberForm, self).clean()
        msisdn = cleaned_data.get("msisdn").replace("-", "")[:10]
        contact_phone = cleaned_data.get("contact_phone").replace("-", "")[:10]
        cleaned_data['msisdn'] = msisdn
        cleaned_data['contact_phone'] = contact_phone
        
        return cleaned_data

base/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm
from django.views.decorators.csrf import csrf_exempt

from django.contrib.auth import authenticate, login, logout

from django.contrib import messages

from django.contrib.auth.models import User
from django.views.decorators.http import require_POST

from .models import *
from .forms import *
from .filters import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def registrationPage(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Акаунт создан: ' + user)
             
            return redirect('login')
 
    context = {'form':form}
    return render(request, 'accounts/registration.html', context)


def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password )

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.info(request, 'Логин или пароль неверны')

    context = {}
    return render(request, 'accounts/login.html', context)


def home(request):
    context = {}
    operator = request.GET.get('operator', None)
    filters = {}
    is_rent = request.GET.get('is_rent', None)
    if is_rent is not None:
        # Починил фильтр, он у вас не правильно был написан
        if is_rent == '0':
            filters['is_rent'] = False
            context['this_page'] = 'buy'
        elif is_rent == '1':
            filters['is_rent'] = True
            context['this_page'] = 'order'
    prefix = request.GET.get('prefix', None)
    if prefix is not None:
        context['prefix'] = prefix
        prefix = prefix.replace("*", ".")
    else:
        prefix = "..."
    term = request.GET.get('term', None)
    if term is not None:
        context['term'] = term
        term = term.replace("-", "").replace("*", ".")
        if len(term) == 7:
            filters['msisdn__regex']=r'^%s%s' % (prefix, term)
        else:
            filters['msisdn__regex']=r'^%s' % prefix
    elif prefix is not None:
        filters['msisdn__regex']=r'^%s' % prefix
    if operator is not None:
        if operator == 'activ':
            filters['operator'] = 1
        if operator == 'kcell':
            filters['operator'] = 2
        if operator == 'altel':
            filters['operator'] = 3
        if operator == 'tele2':
            filters['operator'] = 4
        if operator == 'beeline':
            filters['operator'] = 5
        if operator == 'izi':
            filters['operator'] = 6

    item_list = PhoneNumber.objects.filter(**filters).all().order_by('-created')
    top_items = PhoneNumber.objects.filter(is_top=True).all()
    page_size = 20
    paginator = Paginator(item_list, page_size)
    page = request.GET.get('page', 1)
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)
    context['items'] = items
    context["top_items"] = top_items
    return render(request, 'base/index.html', context)


def detail(request, id):
    item = PhoneNumber.objects.get(pk=id)
    context = {'item': item}
    return render(request, 'base/detail.html', context)


def my(request):
    context = {}
    user = request.user
    item_list = PhoneNumber.objects.filter(owner__id=user.pk).all()
    page_size = 20 
    paginator = Paginator(item_list, page_size)
    page = request.GET.get('page', 1)
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)
    context['items'] = items
    return render(request, 'base/my.html', context)


def add(request):
    user = request.user
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PhoneNumberForm(request.POST, user=user)
        # check whether it's valid:
        if form.is_valid():
            form.save()
            return redirect('/my/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = PhoneNumberForm(user=user)

    return render(request, 'base/add.html', {'form': form})


def edit(request, id):
    user = request.user
    item = PhoneNumber.objects.get(pk=id, owner=user)
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PhoneNumberForm(request.POST, instance=item)
        # check whether it's valid:
        if form.is_valid():
            form.save()
            return redirect('/my/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = PhoneNumberForm(instance=item)

    return render(request, 'base/edit.html', {'form': form, 'item': item})


def delete(request, id):
    user = request.user
    if request.method == 'POST':
        item = PhoneNumber.objects.filter(pk=id, owner=user).delete()
    return redirect("/my/")


# Обработка страница продавца
def profileSeller(request, id):
    # Получаю профиль продавца через id использовав стандартную модель пользователя
    seller = User.objects.get(id=id)
    numbers = PhoneNumber.objects.filter(owner=seller)
    context = {'seller': seller,
               'numbers': numbers}
    return render(request, 'accounts/seller_account.html', context)


# Получение номера телефона
@csrf_exempt
@require_POST   # Обрабатываю только пост запросы
def find_number(request):
    ajax_prefix = request.POST.get('prefix')
    ajax_number = request.POST.get('number')
    full_number = f'{ajax_prefix}{ajax_number}'.replace('-', '').strip()

    # Проверка на какой странице находится юзер: Главная, Купить, Аренда.
    # В зависимости от этого фильтровать номера телефонов
    category = request.POST.get('filter')

    if category == 'buy':
        all_numbers = PhoneNumber.objects.filter(is_rent=False).order_by('-created')
    elif category == 'order':
        all_numbers = PhoneNumber.objects.filter(is_rent=True).order_by('-created')
    else:
        all_numbers = PhoneNumber.objects.all().order_by('-created')

    find_numbers = []
    for number in all_numbers:
        flag = True

        # Перебираю соответствующие элементы списков
        for symbolFindNumber, symbolNumberDB in zip(full_number, number.msisdn):
            # Если символ введённого юзером номера не является звёздочкой(пустым) и если этот же символ
            # не равняется символу перебираемого номераз из ДБ, то этот номер не проходит фильтр
            if symbolFindNumber != '*' and symbolFindNumber != symbolNumberDB:
                flag = False

        # Если номер прошёл фильтр, создаём для него json и добавляем в список
        if flag:
            json_number = {
                'operator': number.get_operator_display(),
                'msisdn': number.msisdn,
                'price': number.price,
                'is_rent': number.is_rent,
                'link': number.get_absolute_url(),
                'css_class': number.css_class,
            }
            find_numbers.append(json_number)

    return JsonResponse({'find_numbers': find_numbers})

base/templates/base/add.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}

    <div class="form_add_number">
        <form method="POST" action="/add/">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-success" type="submit">Добавить</button>
        </form>
    </div>


{% endblock content %}

{% block scripts %}
<script type="text/javascript">
     $(document).ready(function () {
        $("input[name=msisdn]").mask("**********", { placeholder: "", autoclear: false});
        $("input[name=contact_phone]").mask("**********", { placeholder: "", autoclear: false});
    });
</script>
{% endblock  %}

base/templates/base/detail.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}

<div class="purchase-form">

    <div class="purchase-form-top">
        <div class="purchase-logo"><img src="" alt=""></div>
        <div class="purchase-num">
            <p class="numer-pure">+7{{item.msisdn}}</p>
        </div>
    </div>

    <div class="purchase-form-middle">
        <ul>
            <li>Оператор: {{item.get_operator_display}}</li>
            <li>ЦЕНА: {{item.price}} &#8376;</li>
            <li>ИМЯ ПРОДАВЦА: <a href="{% url 'seller' item.owner.id %}">{{item.owner}}</a></li>
            <li>ГОРОД: {{item.get_city_display}}</li>
            <li>КОНТАКТЫ: <a href="tel:+{{item.contact_phone}}">{{item.contact_phone}}</a></li>
            <li>ОПИСАНИЕ: {{item.desctiption}}</li>
        </ul>
    </div>

    <div class="purchase-form-bottom">
        <ul class="two-button">
            <li><a href="tel:+{{item.contact_phone}}">Позвонить</a></li>
            <li><a href="">Написать</a></li>
        </ul>
    </div>
</div>


<div class="comment">
    <a href="">Оставить комментарий</a>
</div>

<div class="regbut-pure">
    <a href="{% url 'registration' %}">Регистрация</a> / <a href="{%url 'login'%}">Вход</a>
</div>
{% endblock content %}

base/templates/base/edit.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}

    <div class="form_add_number">
        <form method="POST" action="/edit/{{item.pk}}/">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-warning">Изменить</button>
        </form>

        <form method="POST" action="/delete/{{item.pk}}/">
            {% csrf_token %}
            <button class="btn btn-danger">Удалить</button>
        </form>
    </div>

{% endblock content %}

{% block scripts %}
<script type="text/javascript">
     $(document).ready(function () {
        $("input[name=msisdn]").mask("**********", { placeholder: "**********", autoclear: false});
        $("input[name=contact_phone]").mask("**********", { placeholder: "**********", autoclear: false});
    });
</script>
{% endblock  %}

base/templates/base/footer.html
<?php

//echo('ТАК');	
?>

{% load static %}

<div class="footer">
	<div class="footer__inner">
		
		<div class="footer" style="background-image: url("{% static 'img/back.png' %}">
		
		<ul>
			<li>Email:<a href="mailto:Simkard@internet.ru" class="footer__email"> simkard@internet.ru</a></li>
			<li>Написать WhatsApp: <a href="https://api.whatsapp.com/send?phone=77071212321&text=%D0%A5%D0%BE%D1%87%D1%83%20%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D0%B0%D1%82%D1%8C%20%D0%BD%D0%BE%D0%BC%D0%B5%D1%80" class="footer__whatsapp" target="_blank" >+7(776)776-01-01</a></li>
		</ul>


	</div>
</div>

base/templates/base/header.html
<div class="header">
	<div class="header__section">
		<div class="header__item1 headerButton" id="link-home"><a href="{% url 'home' %}" class="btn-2">Главная</a></div>

		<div class="regbut">
			{% if user.is_authenticated %}
			{{user.username}}
			<a href="/my">Мои номера</a>
			{% else %}
			<a href="{% url 'registration' %}">Регистрация  </a> /
			<a href="{% url 'login' %}"> Вход</a>
			{% endif %}

		</div>
	</div>


	<div class="header__section">
		<div class="header__item2" id="header__item2">
			<ul class="menu">
				<li><a href="?is_rent=0" class="btn-2 {% if this_page == 'buy' %}this_page{% endif %}">Купить</a></li>
				<li><a href="?is_rent=1" class="btn-2 {% if this_page == 'order' %}this_page{% endif %}">Аренда</a></li>
			</ul>


		</div>

	</div>
</div>

base/templates/base/index.html
{% extends 'base/main.html' %}

{% load static %}
{% load my_tags %}

{% block content %}


<h1 class="subtitle">Подбор номера</h1>
<div class="topsearch">
    <div class="form-group">
        <h1 class="seven">+7</h1>
        <input id="prefix" placeholder="***" type="tel" class="form-control" autocomplete="off" name="prefix" value="{{prefix}}">
        <input id="phone" placeholder="***-**-**" type="tel" class="form-control" autocomplete="off" name="term" value="{{term}}">
    </div>
</div>

<img src="{% static 'img/simhand.png'%}" alt="" style="position: absolute; width: 250px;height: 200px; right: 150px; margin-top: -280px; opacity: 30%;">

<div class="titletop">
    <h2>ТОП</h2>

</div>


<div class="numbers__box1">
    <div class="parent">
        {% for item in top_items %}
        <tr>
            <td>
                <a href="{%url 'detail' item.pk%}" class="topnum">+7{{item.msisdn}}</a>
            </td>
        </tr>
        {% endfor %}
    </div>
</div>





<div class="bottom__operators">
    <div class="operators__inner">

        <button class="button-three beeline">
            <a href="/?operator=beeline"><img src="{% static 'img/beeline-m.png' %}" style="margin-bottom: 3px;" />BEELINE</a>
        </button>

        <button class="button-three activ">
            <a href="/?operator=activ"><img src="{% static 'img/activ.png' %}" style="width: 30px;height: 30px;margin-bottom: 3px; margin-right:8px;">ACTIV</a>
        </button>

        <button class="button-three kcell">
            <a href="/?operator=kcell"><img src="{% static 'img/kcell-m.png' %}" style="margin-bottom: 3px; margin-right:5px;">KCELL</a>
        </button>

        <button class="button-three tele2">
            <a href="/?operator=tele2">TELE2</a>
        </button>

        <button class="button-three altel">
            <a href="/?operator=altel"><img src="{% static 'img/Altel.png' %}" style="width: 30px;height: 30px;margin-bottom:4px;">LTEL</a>
        </button>

        <button class="button-three izi">
            <a href="/?operator=izi"><img src="{% static 'img/izi.png' %}" style="width:30px;height:30px;margin-bottom: 4px; ">IZI</a>
        </button>

    </div>

</div>


<div class="numbers__box2">
    <div class="parent2">
        {% for item in items %}
        <tr>
            <td>
                <div class="title__numbers">
                    <h6 class="{{item.css_class}}">{{item.get_operator_display}}</h6>
                    <div class="seven2">
                        <h4>+7</h4>
                        <div class="topnumbox2">
                            <a href="{%url 'detail' item.pk%}" class="topnum2">{{item.msisdn}}</a>
                        </div>
                    </div>
                    <h6 class="title__sell">{{item.price_html}}</h6>
                </div>
            </td>
        </tr>
        {% endfor %}
    </div>
    {% if items.has_other_pages %}

    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if items.has_previous %}
              <li class="page-item"><a class="page-link" href="?{% param_replace page=items.previous_page_number %}"></a></li>
            {% else %}
              <li class="disabled page-item"><span></span></li>
            {% endif %}
            {% for i in items.paginator.page_range %}
              {% if items.number == i %}
                  <li class="page-item active"><a class="page-link"><span>{{ i }} <span class="sr-only">(Текущая)</span></span></a></li>
              {% else %}
                <li class="page-item"><a class="page-link" href="?{% param_replace page=i %}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if users.has_next %}
              <li class="page-item"><a class="page-link" href="?{% param_replace page=items.next_page_number %}"></a></li>
            {% else %}
              <li class="disabled page-item"><span></span></li>
            {% endif %}
      </ul>
  </nav>
{% endif %}
</div>
{% endblock content %}


{% block scripts %}
{#  Необходимы для работы с ajax запросами  #}
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>


{# непосредственно js код для поиска номера #}
<script>
    // Нужно для безопасной работы ajax запросов
    let csrftoken = Cookies.get('csrftoken');

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    // Получаю значения из полей ввода номера телефона
    let phone = document.querySelector('#phone');
    let prefix = document.querySelector('#prefix');

    let previous_search = '';

    // Фильтрую данные, чтобы потом отправить запрос на сервак
    function send_number() {
        let ajax_prefix = prefix.value, ajax_number = phone.value;

        let full_number = ajax_prefix + ajax_number;
        // Делаю проверку, чтобы при перемещении курсора не отправлялся аякс запрос
        if (previous_search !== full_number) {
            get_find_numbers(ajax_prefix, ajax_number);
        }
        previous_search = full_number;
    }

    // А это уже непосредственно работа с ajax
    function get_find_numbers(ajax_prefix, ajax_number) {
        // Отправляю запрос
        $.post('{% url 'find_number' %}', {
            prefix: ajax_prefix,
            number: ajax_number,
            filter: '{{ this_page }}',
        }, function(data) {
            // Начинаю обрабатывать
            let clear_numbers = document.querySelector('.numbers__box2 .parent2');
            // Очищаю блок от номеров, которые в нём были ранее
            clear_numbers.innerHTML = '';

            // Перевожу полученный ответ в виде строки в json
            data = JSON.parse(data);
            let numbers = data['find_numbers'];

            // Перебираю все найденные номера
            for (number of numbers) {
                // Закидываю параметры номера в переменные
                let msisdn = number['msisdn'];
                let operator = number['operator'];
                let price = number['price'];
                let is_rent = number['is_rent'];
                let link = number['link'];
                let css_class = number['css_class'];

                // Начинаю формировать html код конкретного номера
                let country_code = document.createElement('h4');
                country_code.innerText = '+7';

                let block_text_number = document.createElement('div');
                block_text_number.classList.add('topnumbox2');
                block_text_number.innerHTML = `<a href="${link}" class="topnum2">${msisdn}</a>`;

                let block_wrapper = document.createElement('div');
                block_wrapper.classList.add('seven2');
                block_wrapper.appendChild(country_code);
                block_wrapper.appendChild(block_text_number);

                let block_operator = document.createElement('h6');
                block_operator.classList.add(`${css_class}`);
                block_operator.innerText = `${operator}`;

                let block_price = document.createElement('h6');
                block_price.classList.add('title__sell');
                if (is_rent) {
                    block_price.innerText = `${price} тг/мес`;
                } else {
                    block_price.innerText = `${price} тг`;
                }

                let main_block = document.createElement('div');
                main_block.classList.add('title__numbers');
                main_block.appendChild(block_operator);
                main_block.appendChild(block_wrapper);
                main_block.appendChild(block_price);

                // В ранее очищенный блок закидываю очередной номер
                clear_numbers.appendChild(main_block);
            }
        });
    }

    // Получение изменения поля и вызов функции, которая будет обрабатывать полученный номер от юзера
    phone.onkeyup = phone.oninput = prefix.onkeyup = prefix.oninput = send_number;
    phone.onpropertychange = prefix.onpropertychange = function(event) {
        if (event.propertyName == "value") send_number();
    }
    phone.oncut = prefix.onpropertychange = function() {
        setTimeout(send_number, 0);
    }
</script>
{% endblock %}

base/templates/base/main.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Coda+Caption:wght@800&display=swap" rel="stylesheet">
    <title>Simkard.kz</title>
</head>
<body>
    <div class="conteiner__block">

        {% include 'base/header.html' %}

        {% block content %}

        {% endblock content %}

        {% include 'base/footer.html' %}



    </div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <!--<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" type="text/javascript"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery.maskedinput@1.4.1/src/jquery.maskedinput.min.js" type="text/javascript"></script>-->
    <script type="text/javascript" src="../../static/js/newJS/jquery.min.js"></script>
    <script type="text/javascript" src="../../static/js/newJS/jquery-ui.min.js"></script>
    <script type="text/javascript" src="../../static/js/newJS/jquery.maskedinput-1.2.2.js" ></script>

    <script type="text/javascript">

        $("#prefix").mask("***", { placeholder: "*", autoclear: false});
        $("#phone").mask("***-**-**", { placeholder: "*", autoclear: false});
    </script>

    {% block scripts %}
    {% endblock %}

    <script type="text/javascript">

        $(document).ready(function () {

            // Get current page URL
            var url = window.location.href;

            // remove # from URL
            url = url.substring(0, (url.indexOf("#") == -1) ? url.length : url.indexOf("#"));

            // remove parameters from URL
            url = url.substring(0, (url.indexOf("?") == -1) ? url.length : url.indexOf("?"));

            // select file name
            url = url.substr(url.lastIndexOf("/") + 1);

            // If file name not avilable
            if (url == '') {
                url = 'index.html';
            }

            // Loop all menu items
            $('.menu li').each(function () {

                // select href
                var href = $(this).find('a').attr('href');

                // Check filename
                if (url == href) {

                    // Add active class
                    $(this).addClass('active');
                }
            });
        });
    </script>


</body>
</html>

base/templates/base/my.html
{% extends 'base/main.html' %}

{% load static %}
{% load my_tags %}

{% block content %}

<div class="add_number">
    <button type="button" class="btn btn-outline-secondary"><a href="/add">Добавить номер</a></button>
</div>


<div class="numbers__box2">
    <div class="parent2">
        {% for item in items %}
        <tr>
            <td>
                <div class="title__numbers">
                    <h6 class="{{item.css_class}}">{{item.get_operator_display}}</h6>
                    <div class="seven2">
                        <h4>+7</h4>
                        <div class="topnumbox2">
                            <a href="{%url 'edit' item.pk%}" class="topnum2">{{item.msisdn}}</a>
                        </div>
                    </div>
                    <h6 class="title__sell">{{item.price_html}}</h6>
                </div>
            </td>
        </tr>
        {% endfor %}
    </div>
    {% if items.has_other_pages %}
    
        <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if items.has_previous %}
              <li class="page-item"><a class="page-link" href="?{% param_replace page=items.previous_page_number %}"></a></li>
            {% else %}
              <li class="disabled page-item"><span></span></li>
            {% endif %}
            {% for i in items.paginator.page_range %}
              {% if items.number == i %}
                <li class="page-item active"><a class="page-link"><span>{{ i }} <span class="sr-only">(Текущая)</span></a></li>
              {% else %}
                <li class="page-item"><a class="page-link" href="?{% param_replace page=i %}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if users.has_next %}
              <li class="page-item"><a class="page-link" href="?{% param_replace page=items.next_page_number %}"></a></li>
            {% else %}
              <li class="disabled page-item"><span></span></li>
            {% endif %}
      </ul>
  </nav>
{% endif %}
</div>
{% endblock content %}

base/templates/base/profile.html
{% extends 'base/main.html' %}

{% block content %}

<h1>Profile Template</h1>

{% endblock content %}